name: oss_flutter
description: Aliyun Oss Client for flutter.
version: 0.1.5
author: Alexander.Li<superpowerlee@gmail.com>
homepage: https://github.com/ipconfiger/oss_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  intl: any
  xml: ^5.1.2


dev_dependencies:
  test: ^1.17.9
  http_client: ^1.5.1
