name: oss_flutter
description: Aliyun Oss Client for flutter.
version: 0.1.5
homepage: https://github.com/ipconfiger/oss_flutter

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  crypto: ^3.0.3
  intl: any
  xml: ^6.4.2


dev_dependencies:
  test: ^1.17.9
  http_client: ^1.5.1
